#!/bin/bash
drwxr-xr-x    1 root root  160 Nov 29 14:10 .                                                                                                                           
drwxr-xr-x    1 root root  160 Nov 29 14:10 ..                                                                                                                          
-rw-r--r--    1 root root    7 Nov 28 19:12 0x01_emacs                                                                                                                  
drwxr-xr-x    4 root root   51 Nov 29 14:40 alx-zero_day                                                                                                                
lrwxrwxrwx    1 root root    7 Mar 16  2022 bin -> usr/bin                                                                                                              
drwxr-xr-x    2 root root    6 Apr 15  2020 boot                                                                                                                        
drwxr-xr-x    5 root root  340 Dec  3 02:10 dev                                                                                                                         
-rwxr-xr-x    1 root root    0 Nov 16 11:04 .dockerenv                                                                                                                  
drwxr-xr-x    1 root root   37 Nov 16 11:04 etc                                                                                                                         
-rw-r--r--    1 root root  143 Dec  5 13:04 file1.html                                                                                                                  
drwxr-xr-x    8 root root  229 Dec  5 13:25 .git                                                                                                                        
drwxr-xr-x    2 root root    6 Apr 15  2020 home                                                                                                                        
lrwxrwxrwx    1 root root    7 Mar 16  2022 lib -> usr/lib                                                                                                              
lrwxrwxrwx    1 root root    9 Mar 16  2022 lib32 -> usr/lib32                                                                                                          
lrwxrwxrwx    1 root root    9 Mar 16  2022 lib64 -> usr/lib64                                                                                                          
lrwxrwxrwx    1 root root   10 Mar 16  2022 libx32 -> usr/libx32                                                                                                        
drwxr-xr-x    1 root root   47 Nov 22 13:39 media                                                                                                                       
drwxr-xr-x    2 root root    6 Mar 16  2022 mnt                                                                                                                         
drwxr-xr-x    1 root root   19 Mar 29  2022 opt                                                                                                                         
dr-xr-xr-x 1515 root root    0 Dec  3 02:10 proc                                                                                                                        
-rw-r--r--    1 root root   51 Nov 28 20:59 README.md                                                                                                                   
drwx------    1 root root 4096 Dec  3 02:12 root                                                                                                                        
drwxr-xr-x    1 root root   22 Nov 16 11:04 run                                                                                                                         
lrwxrwxrwx    1 root root    8 Mar 16  2022 sbin -> usr/sbin                                                                                                            
drwxr-xr-x    2 root root    6 Mar 16  2022 srv                                                                                                                         
dr-xr-xr-x   13 root root    0 Dec  3 02:10 sys                                                                                                                         
drwxrwxrwt    1 root root   82 Nov 29 14:10 tmp                                                                                                                         
drwxr-xr-x    1 root root  109 Mar 29  2022 usr                                                                                                                         
drwxr-xr-x    1 root root   30 Mar 16  2022 var  
